name = "mdworks-hospitality-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CONTENT"
id = "19973468f54b4708b9e852d70eab6c39"

[vars]
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/iq9ymgpz2g"
